language: ruby
bundler_args: --without debug
script: "bundle exec rspec spec"
env:
  - CI=true
rvm:
  - 2.0
  - 2.1
  - 2.2.4
  - 2.3
  - jruby-9.0.4.0
  - rbx-2
cache: bundler
sudo: false
matrix:
  allow_failures:
    - rvm: jruby-9.0.4.0
    - rvm: rbx-2

